// This file maps open_cart_collection_id to an array of ring category objects
export const ringCategoryData: Record<number, Array<{
  filter_id: number;
  filter_class: string;
  filter_selected: number;
  dropdown: number;
  static_filter: number;
  short_name: string;
  display: number;
  name: string;
  title_name: string;
  code: string;
}>> = {
    1: [
      {
        filter_id: 282,
        filter_class: 'sale',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Sale',
        display: 0,
        name: 'Sale',
        title_name: 'Sale',
        code: '',
      },
      {
        filter_id: 58,
        filter_class: 'classic_solitaire',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Solitaire',
        display: 1,
        name: 'Classic Solitaire',
        title_name: 'Solitaire',
        code: 'SOLITAIRE',
      },
      {
        filter_id: 59,
        filter_class: 'halo_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Halo',
        display: 1,
        name: 'Halo Ring',
        title_name: 'Halo',
        code: 'HALO-RING',
      },
      {
        filter_id: 60,
        filter_class: 'side_stone_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Side Stone',
        display: 1,
        name: 'Side Stone Ring',
        title_name: 'Side Stone',
        code: 'SIDE-STONE',
      },
      {
        filter_id: 61,
        filter_class: 'three_stone',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Three Stone',
        display: 1,
        name: 'Three Stone',
        title_name: 'Three Stone',
        code: 'THREE-STONE',
      },
      {
        filter_id: 149,
        filter_class: 'cluster_engagement_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Cluster Rings',
        display: 0,
        name: 'Cluster Engagement Ring',
        title_name: 'Cluster Rings',
        code: 'CLUSTER-RING',
      },
      {
        filter_id: 150,
        filter_class: 'illusion_set_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Illusion Set',
        display: 1,
        name: 'Illusion Set Ring',
        title_name: 'Illusion Set',
        code: 'ILLUSION-RING',
      },
      {
        filter_id: 472,
        filter_class: 'toi_et_moi',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Toi Et Moi',
        display: 1,
        name: 'Toi Et Moi',
        title_name: 'Toi Et Moi',
        code: 'TOI-ET-MOI',
      },
      {
        filter_id: 245,
        filter_class: 'couples',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Couples',
        display: 1,
        name: 'Couples',
        title_name: 'Couples',
        code: 'COUPLE-RING',
      },
      {
        filter_id: 101,
        filter_class: 'trilogy_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Trilogy',
        display: 1,
        name: 'Trilogy Ring',
        title_name: 'Trilogy',
        code: 'THREE-STONE-RING',
      },
      {
        filter_id: 174,
        filter_class: 'twisted_engagement_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Twisted',
        display: 1,
        name: 'Twisted Engagement Ring',
        title_name: 'Twisted Engagement Ring',
        code: 'TWISTED-RING',
      },
      {
        filter_id: 165,
        filter_class: 'gemstone_engagement_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Gemstone',
        display: 1,
        name: 'Gemstone Engagement Ring',
        title_name: 'Gemstone',
        code: 'GEMSTONE-ENGAGEMENT-RING',
      },
      {
        filter_id: 500,
        filter_class: 'diamond_band',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Diamond Band',
        display: 1,
        name: 'Diamond Band',
        title_name: 'Diamond Band',
        code: 'DIABND',
      },
      {
        filter_id: 169,
        filter_class: 'unique_engagement_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Unique',
        display: 1,
        name: 'Unique Engagement Ring',
        title_name: 'Unique',
        code: 'UNIQUE-RING',
      },
      {
        filter_id: 170,
        filter_class: 'unusual_engagement_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Unusual',
        display: 1,
        name: 'Unusual Engagement Ring',
        title_name: 'Unusual',
        code: 'UNUSUAL-RING',
      },
      {
        filter_id: 171,
        filter_class: 'antique_engagement_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Antique',
        display: 1,
        name: 'Antique Engagement Ring',
        title_name: 'Antique',
        code: 'ANTIQUE-RING',
      },
      {
        filter_id: 172,
        filter_class: 'vintage_engagement_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Vintage',
        display: 1,
        name: 'Vintage Engagement Ring',
        title_name: 'Vintage',
        code: 'VINTAGE-ENGAGEMENT-RING',
      },
      {
        filter_id: 161,
        filter_class: 'minimalist_engagement_rings',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Minimalist',
        display: 1,
        name: 'Minimalist Engagement Rings',
        title_name: 'Minimalist',
        code: 'MINIMALIST-RING',
      },
      {
        filter_id: 501,
        filter_class: 'mens',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: "Men's Rings",
        display: 1,
        name: "Men's Rings",
        title_name: "Men's Rings",
        code: '',
      },
      {
        filter_id: 502,
        filter_class: 'womens',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: "Women's Rings",
        display: 1,
        name: "Women's Rings",
        title_name: "Women's Rings",
        code: '',
      },
      {
        filter_id: 503,
        filter_class: 'black_diamond',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Black Diamond Rings',
        display: 1,
        name: 'Black Diamond Rings',
        title_name: 'Black Diamond Rings',
        code: '',
      },
      {
        filter_id: 504,
        filter_class: 'ruby',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Ruby Rings',
        display: 1,
        name: 'Ruby Rings',
        title_name: 'Ruby Rings',
        code: '',
      },
      {
        filter_id: 505,
        filter_class: 'tanzanite',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Tanzanite Rings',
        display: 1,
        name: 'Tanzanite Rings',
        title_name: 'Tanzanite Rings',
        code: '',
      },
      {
        filter_id: 506,
        filter_class: 'emeralds',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Emerald Rings',
        display: 1,
        name: 'Emerald Rings',
        title_name: 'Emerald Rings',
        code: '',
      },
      {
        filter_id: 507,
        filter_class: 'blue_sapphire',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Blue Sapphire Rings',
        display: 1,
        name: 'Blue Sapphire Rings',
        title_name: 'Blue Sapphire Rings',
        code: '',
      },
      {
        filter_id: 508,
        filter_class: 'aquamarine',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Aquamarine Rings',
        display: 1,
        name: 'Aquamarine Rings',
        title_name: 'Aquamarine Rings',
        code: '',
      },
      {
        filter_id: 509,
        filter_class: 'moissanite',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Moissanite Rings',
        display: 1,
        name: 'Moissanite Rings',
        title_name: 'Moissanite Rings',
        code: '',
      },
      {
        filter_id: 510,
        filter_class: 'oval',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Oval Rings',
        display: 1,
        name: 'Oval Rings',
        title_name: 'Oval Rings',
        code: '',
      },
      {
        filter_id: 511,
        filter_class: 'amethyst',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Amethyst Rings',
        display: 1,
        name: 'Amethyst Rings',
        title_name: 'Amethyst Rings',
        code: '',
      },
    ],
    2: [
        {
        filter_id: 72,
        filter_class: 'cluster_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Black Cluster',
        display: 1,
        name: 'Cluster Ring',
        title_name: 'Black Cluster',
        code: 'CLUSTER-RING',
        },
        {
        filter_id: 59,
        filter_class: 'halo_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Halo',
        display: 1,
        name: 'Halo Ring',
        title_name: 'Halo',
        code: 'HALO-RING',
        },
        {
        filter_id: 61,
        filter_class: 'three_stone',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Three Stone',
        display: 1,
        name: 'Three Stone',
        title_name: 'Three Stone',
        code: 'THREE-STONE',
        },
        {
        filter_id: 64,
        filter_class: 'two_stone',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Two Stone',
        display: 1,
        name: 'Two Stone',
        title_name: 'Two Stone',
        code: 'TWO-STONE',
        },
        {
        filter_id: 473,
        filter_class: 'unusual_eternity_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Unusual Eternity Rings',
        display: 1,
        name: 'Unusual Eternity Ring',
        title_name: 'Unusual Eternity Rings',
        code: 'UNUSUAL-ETERNITY',
        },
        {
        filter_id: 245,
        filter_class: 'couples',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Couples',
        display: 1,
        name: 'Couples',
        title_name: 'Couples',
        code: 'COUPLE-RING',
        },
        {
        filter_id: 65,
        filter_class: 'five_stone',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Five Stone',
        display: 1,
        name: 'Five Stone',
        title_name: 'Five Stone',
        code: 'FIVE-STONE-RING',
        },
        {
        filter_id: 66,
        filter_class: 'seven_stone',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Seven Stone',
        display: 1,
        name: 'Seven Stone',
        title_name: 'Seven Stone',
        code: 'SEVEN-STONE-RING',
        },
        {
        filter_id: 234,
        filter_class: 'all_eternity',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'All Eternity',
        display: 1,
        name: 'All Eternity',
        title_name: 'All Eternity',
        code: 'FULL-ETERNITY-DIAMOND',
        },
        {
        filter_id: 186,
        filter_class: 'band',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Band',
        display: 1,
        name: 'Band',
        title_name: 'Band',
        code: 'BANDS-RING',
        },
        {
        filter_id: 188,
        filter_class: 'engagement',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Engagement',
        display: 0,
        name: 'Engagement',
        title_name: 'Engagement',
        code: '',
        },
        {
        filter_id: 67,
        filter_class: 'half_eternity',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Half Eternity',
        display: 1,
        name: 'Half Eternity',
        title_name: 'Half Eternity',
        code: 'HALF-ETERNITY',
        },
        {
        filter_id: 241,
        filter_class: 'promise_rings',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Promise',
        display: 1,
        name: 'Promise Rings',
        title_name: 'Promise Rings',
        code: 'PROMISE-RINGS',
        },
        {
        filter_id: 68,
        filter_class: 'full_eternity',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Full Eternity',
        display: 1,
        name: 'Full Eternity',
        title_name: 'Full Eternity',
        code: 'FULL-ETERNITY',
        },
        {
        filter_id: 69,
        filter_class: 'eternity_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Eternity',
        display: 1,
        name: 'Eternity Ring',
        title_name: 'Eternity',
        code: 'ETERNITY-RING',
        },
        {
        filter_id: 101,
        filter_class: 'trilogy_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Trilogy',
        display: 1,
        name: 'Trilogy Ring',
        title_name: 'Trilogy',
        code: 'THREE-STONE-RING',
        },
        {
        filter_id: 533,
        filter_class: 'initial_diamond_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Initial Diamond Ring',
        display: 1,
        name: 'Initial Diamond Ring',
        title_name: 'Initial Diamond Ring',
        code: 'INIRING',
        },
        {
        filter_id: 471,
        filter_class: 'stacking_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Stacking Ring',
        display: 1,
        name: 'Stacking Ring',
        title_name: 'Stacking Ring',
        code: 'STACKING-RING',
        },
        {
        filter_id: 499,
        filter_class: 'flower_diamond',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Flower Diamond',
        display: 1,
        name: 'Flower Diamond',
        title_name: 'Flower Diamond',
        code: 'FLDIA',
        },
        {
        filter_id: 162,
        filter_class: 'minimalist_diamond_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Minimalist',
        display: 1,
        name: 'Minimalist Diamond Ring',
        title_name: 'Minimalist',
        code: 'DELICATE-RING',
        },
        {
        filter_id: 152,
        filter_class: 'gemstone_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Gemstone',
        display: 1,
        name: 'Gemstone Ring',
        title_name: 'Gemstone',
        code: 'GEMSTONE-RING',
        },
        {
        filter_id: 534,
        filter_class: 'baguette',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Baguette Rings',
        display: 1,
        name: 'Baguette Rings',
        title_name: 'Baguette Rings',
        code: '',
        },
    ],
    3: [
        {
        filter_id: 245,
        filter_class: 'couples',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Couples',
        display: 1,
        name: 'Couples',
        title_name: 'Couples',
        code: 'COUPLE-RING',
        },
        {
        filter_id: 474,
        filter_class: 'unique_eternity_band',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Unique Eternity Bands',
        display: 1,
        name: 'Unique Eternity Band',
        title_name: 'Unique Eternity Bands',
        code: 'UNIQUE-WEDDING',
        },
        {
        filter_id: 475,
        filter_class: 'unique_mens_wedding_band',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Unique Mens Wedding Bands',
        display: 1,
        name: 'Unique Mens Wedding Band',
        title_name: 'Unique Mens Wedding Bands',
        code: 'UNIQUE-MENS-WEDDING',
        },
        {
        filter_id: 67,
        filter_class: 'half_eternity',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Half Eternity',
        display: 1,
        name: 'Half Eternity',
        title_name: 'Half Eternity',
        code: 'HALF-ETERNITY',
        },
        {
        filter_id: 535,
        filter_class: 'plain_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Plain Ring',
        display: 1,
        name: 'Plain Ring',
        title_name: '',
        code: 'plain-ring',
        },
        {
        filter_id: 476,
        filter_class: 'vintage_wedding_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Vintage Wedding Rings',
        display: 1,
        name: 'Vintage Wedding Ring',
        title_name: 'Vintage Wedding Rings',
        code: 'VINTAGE-WEDDING',
        },
        {
        filter_id: 68,
        filter_class: 'full_eternity',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Full Eternity',
        display: 1,
        name: 'Full Eternity',
        title_name: 'Full Eternity',
        code: 'FULL-ETERNITY',
        },
        {
        filter_id: 477,
        filter_class: 'unusual_wedding_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Unusual Wedding Rings',
        display: 1,
        name: 'Unusual Wedding Ring',
        title_name: 'Unusual Wedding Rings',
        code: 'UNUSUAL-WEDDING',
        },
        {
        filter_id: 104,
        filter_class: "women's_shaped",
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: "Women's Shaped",
        display: 1,
        name: "Women's Shaped",
        title_name: "Women's Shaped",
        code: 'WOMENS-SHAPED',
        },
        {
        filter_id: 69,
        filter_class: 'eternity_ring',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Eternity',
        display: 1,
        name: 'Eternity Ring',
        title_name: 'Eternity',
        code: 'ETERNITY-RING',
        },
        {
        filter_id: 536,
        filter_class: 'mens',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: "Men's Rings",
        display: 1,
        name: "Men's Rings",
        title_name: "Men's Rings",
        code: '',
        },
        {
        filter_id: 537,
        filter_class: 'womens',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: "Women's Rings",
        display: 1,
        name: "Women's Rings",
        title_name: "Women's Rings",
        code: '',
        },
        {
        filter_id: 538,
        filter_class: 'rose_gold',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Rose Gold Rings',
        display: 1,
        name: 'Rose Gold Rings',
        title_name: 'Rose Gold Rings',
        code: '',
        },
        {
        filter_id: 539,
        filter_class: 'white_gold',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'White Gold Rings',
        display: 1,
        name: 'White Gold Rings',
        title_name: 'White Gold Rings',
        code: '',
        },
        {
        filter_id: 540,
        filter_class: 'yellow_gold',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Yellow Gold Rings',
        display: 1,
        name: 'Yellow Gold Rings',
        title_name: 'Yellow Gold Rings',
        code: '',
        },
        {
        filter_id: 541,
        filter_class: 'emeralds',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Emerald Rings',
        display: 1,
        name: 'Emerald Rings',
        title_name: 'Emerald Rings',
        code: '',
        },
        {
        filter_id: 542,
        filter_class: 'marquise',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Marquise Rings',
        display: 1,
        name: 'Marquise Rings',
        title_name: 'Marquise Rings',
        code: '',
        },
        {
        filter_id: 543,
        filter_class: 'oval',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Oval Rings',
        display: 1,
        name: 'Oval Rings',
        title_name: 'Oval Rings',
        code: '',
        },
        {
        filter_id: 544,
        filter_class: 'pear',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Pear Rings',
        display: 1,
        name: 'Pear Rings',
        title_name: 'Pear Rings',
        code: '',
        },
        {
        filter_id: 545,
        filter_class: 'platinum',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Platinum Rings',
        display: 1,
        name: 'Platinum Rings',
        title_name: 'Platinum Rings',
        code: '',
        },
        {
        filter_id: 546,
        filter_class: 'princess',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Princess Rings',
        display: 1,
        name: 'Princess Rings',
        title_name: 'Princess Rings',
        code: '',
        },
        {
        filter_id: 547,
        filter_class: 'mens plain',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: "Men's Plain Rings",
        display: 1,
        name: "Men's Plain Rings",
        title_name: "Men's Plain Rings",
        code: '',
        },
        {
        filter_id: 548,
        filter_class: 'womens plain',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: "Women's Plain Rings",
        display: 1,
        name: "Women's Plain Rings",
        title_name: "Women's Plain Rings",
        code: '',
        },
    ],
    5: [
        {
        filter_id: 221,
        filter_class: 'necklace',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Necklace',
        display: 0,
        name: 'Necklace',
        title_name: 'Necklace',
        code: '',
        },
        {
        filter_id: 85,
        filter_class: 'solitaire_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Solitaire  Necklaces',
        display: 1,
        name: 'Solitaire Pendant',
        title_name: 'Solitaire  Necklaces',
        code: 'SOLITIRE-PENDANT',
        },
        {
        filter_id: 87,
        filter_class: 'cross_necklace',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Cross',
        display: 1,
        name: 'Cross Necklace',
        title_name: 'Cross',
        code: 'CROSS-PENDANT',
        },
        {
        filter_id: 92,
        filter_class: 'heart_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Heart Necklaces',
        display: 1,
        name: 'Heart Pendant',
        title_name: 'Heart Necklaces',
        code: 'HEART-PENDANT',
        },
        {
        filter_id: 89,
        filter_class: 'circle_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Circle',
        display: 1,
        name: 'Circle Pendant',
        title_name: 'Circle',
        code: 'CIRCLE-PENDANT',
        },
        {
        filter_id: 86,
        filter_class: 'halo_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Halo',
        display: 1,
        name: 'Halo Pendant',
        title_name: 'Halo',
        code: 'HALO-PENDANT',
        },
        {
        filter_id: 118,
        filter_class: 'gemstone_necklace',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Gemstone',
        display: 1,
        name: 'Gemstone Necklace',
        title_name: 'Gemstone',
        code: 'GEMSTONE-PENDANT',
        },
        {
        filter_id: 93,
        filter_class: 'designer_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Designer',
        display: 1,
        name: 'Designer Pendant',
        title_name: 'Designer',
        code: 'DESIGNER-PENDANT',
        },
        {
        filter_id: 90,
        filter_class: 'journey_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Journey',
        display: 1,
        name: 'Journey Pendant',
        title_name: 'Journey',
        code: 'JOURENY-PENDANT',
        },
        {
        filter_id: 91,
        filter_class: 'cluster_necklace',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Cluster Necklaces',
        display: 0,
        name: 'Cluster Necklace',
        title_name: 'Cluster Necklaces',
        code: '',
        },
        {
        filter_id: 121,
        filter_class: 'initial_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Initial',
        display: 1,
        name: 'Initial Pendant',
        title_name: 'Initial',
        code: 'INTIAL-PENDANT',
        },
        {
        filter_id: 94,
        filter_class: 'delicate_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Delicate',
        display: 1,
        name: 'Delicate Pendant',
        title_name: 'Delicate',
        code: 'DELICATE-PENDANT',
        },
        {
        filter_id: 100,
        filter_class: 'drop_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Drop',
        display: 1,
        name: 'Drop Pendant',
        title_name: 'Drop',
        code: 'DROP-BRACELETS',
        },
        {
        filter_id: 119,
        filter_class: 'personalise_pendant',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Personalise',
        display: 1,
        name: 'Personalise Pendant',
        title_name: 'Personalise',
        code: 'PERSONLIZE-PENDANT',
        },
        {
        filter_id: 501,
        filter_class: 'locket',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Locket',
        display: 1,
        name: 'Locket',
        title_name: 'Locket',
        code: 'LCKT',
        },
        {
        filter_id: 227,
        filter_class: 'number_pendants',
        filter_selected: 0,
        dropdown: 1,
        static_filter: 0,
        short_name: 'Number',
        display: 1,
        name: 'Number Pendants',
        title_name: 'Number Pendant',
        code: 'NUMBER-PENDANT',
        },
        {
        filter_id: 502,
        filter_class: 'black_diamond',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Black Diamond Necklaces',
        display: 1,
        name: 'Black Diamond Pendants',
        title_name: 'Black Diamond Pendants',
        code: '',
        },
        {
        filter_id: 503,
        filter_class: 'yellow_gold',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Yellow Gold Necklaces',
        display: 1,
        name: 'Yellow Gold Pendants',
        title_name: 'Yellow Gold Pendants',
        code: '',
        },
        {
        filter_id: 504,
        filter_class: 'platinum',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Platinum Necklaces',
        display: 1,
        name: 'Platinum Pendants',
        title_name: 'Platinum Pendants',
        code: '',
        },
        {
        filter_id: 505,
        filter_class: 'lab_grown_diamond',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Lab Grown Diamond Necklaces',
        display: 1,
        name: 'Lab Grown Diamond Pendants',
        title_name: 'Lab Grown Diamond Pendants',
        code: '',
        },
        {
        filter_id: 506,
        filter_class: 'silver',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Silver Necklaces',
        display: 1,
        name: 'Silver Pendants',
        title_name: 'Silver Pendants',
        code: '',
        },
        {
        filter_id: 507,
        filter_class: 'blue_sapphire',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Blue Sapphire Necklaces',
        display: 1,
        name: 'Blue Sapphire Pendants',
        title_name: 'Blue Sapphire Pendants',
        code: '',
        },
        {
        filter_id: 508,
        filter_class: 'ruby',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Ruby Necklaces',
        display: 1,
        name: 'Ruby Pendants',
        title_name: 'Ruby Pendants',
        code: '',
        },
        {
        filter_id: 509,
        filter_class: 'emeralds',
        filter_selected: 0,
        dropdown: 0,
        static_filter: 1,
        short_name: 'Emerald Necklaces',
        display: 1,
        name: 'Emerald Pendants',
        title_name: 'Emeralds Pendants',
        code: '',
        },
    ],
    6: [
    {
      filter_id: 292,
      filter_class: 'friendship_bracelet',
      filter_selected: 0,
      dropdown: 1,
      static_filter: 0,
      short_name: 'Friendship',
      display: 1,
      name: 'Friendship Bracelet',
      title_name: 'Friendship',
      code: 'FRIENDSHIP',
    },
    {
      filter_id: 95,
      filter_class: 'tennis_bracelet',
      filter_selected: 0,
      dropdown: 1,
      static_filter: 0,
      short_name: 'Tennis',
      display: 1,
      name: 'Tennis Bracelet',
      title_name: 'Tennis',
      code: 'TENNIS-BRACELETS',
    },
    {
      filter_id: 97,
      filter_class: 'delicate_bracelet',
      filter_selected: 0,
      dropdown: 1,
      static_filter: 0,
      short_name: 'Delicate Bracelets',
      display: 1,
      name: 'Delicate Bracelet',
      title_name: 'Delicate Bracelets',
      code: 'DELICATE-BRACELETS',
    },
    {
      filter_id: 99,
      filter_class: 'charm',
      filter_selected: 0,
      dropdown: 1,
      static_filter: 0,
      short_name: 'Charms',
      display: 1,
      name: 'Charm',
      title_name: 'Charms',
      code: 'CHARMS-BRACELETS',
    },
    {
      filter_id: 156,
      filter_class: 'cluster_bracelet',
      filter_selected: 0,
      dropdown: 1,
      static_filter: 0,
      short_name: 'Cluster',
      display: 0,
      name: 'Cluster Bracelet',
      title_name: 'Cluster',
      code: '',
    },
    {
      filter_id: 157,
      filter_class: 'bangles',
      filter_selected: 0,
      dropdown: 1,
      static_filter: 0,
      short_name: 'Bangles',
      display: 1,
      name: 'Bangles',
      title_name: 'Bangles',
      code: 'BANGLE',
    },
    {
      filter_id: 293,
      filter_class: 'silver',
      filter_selected: 0,
      dropdown: 0,
      static_filter: 1,
      short_name: 'Silver Bracelets',
      display: 1,
      name: 'Silver Bracelets',
      title_name: 'Silver Bracelets',
      code: '',
    },
    {
      filter_id: 294,
      filter_class: 'rose_gold',
      filter_selected: 0,
      dropdown: 0,
      static_filter: 1,
      short_name: 'Rose Gold Bracelets',
      display: 1,
      name: 'Rose Gold Bracelets',
      title_name: 'Rose Gold Bracelets',
      code: '',
    },
    {
      filter_id: 295,
      filter_class: 'white_gold',
      filter_selected: 0,
      dropdown: 0,
      static_filter: 1,
      short_name: 'White Gold Bracelets',
      display: 1,
      name: 'White Gold Bracelets',
      title_name: 'White Gold Bracelets',
      code: '',
    },
    {
      filter_id: 296,
      filter_class: 'yellow_gold',
      filter_selected: 0,
      dropdown: 0,
      static_filter: 1,
      short_name: 'Yellow Gold Bracelets',
      display: 1,
      name: 'Yellow Gold Bracelets',
      title_name: 'Yellow Gold Bracelets',
      code: '',
    },
    {
      filter_id: 297,
      filter_class: 'platinum',
      filter_selected: 0,
      dropdown: 0,
      static_filter: 1,
      short_name: 'Platinum Bracelets',
      display: 1,
      name: 'Platinum Bracelets',
      title_name: 'Platinum Bracelets',
      code: '',
    },
    ]
};
