import type { Styles } from "./filteroption.types";

export const styles: Styles = {
	"Style": [
		{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}
	],
	"Metal":[{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}],
	"Stonetype":[{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}],
	"Shape":[{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}],
	"Setting Type":[],
    "By Recipient": [],
    "Carat": [],
}