import type { Styles } from "./filteroption.types";

export const styles: Styles = {
	"Style": [
		{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}
	],
	"Metal":[{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}],
	"Stonetype":[{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}],
	"Shape":[{label: "Classic Solitaire", icon: "solitaire.avif"},
		{label: "Halo Rings", icon: "solitaire.avif"},
		{label: "Side Stone Rings", icon: "solitaire.avif"},
		{label: "Three Stone Rings", icon: "solitaire.avif"},
		{label: "Illusion Set Rings", icon: "solitaire.avif"},
		{label: "Toi Et Moi", icon: "solitaire.avif"},
		{label: "Couples", icon: "solitaire.avif"},
		{label: "Trilogy Rings", icon: "solitaire.avif"},
		{label: "Twisted Rings", icon: "solitaire.avif"},
		{label: "Gemstone", icon: "solitaire.avif"},
		{label: "Diamond Band", icon: "solitaire.avif"},
		{label: "Unique", icon: "solitaire.avif"},
		{label: "Unusual", icon: "solitaire.avif"},
		{label: "Antique", icon: "solitaire.avif"},
		{label: "Vintage", icon: "solitaire.avif"},
		{label: "Minimalist", icon: "solitaire.avif"}],
	"Setting Type":[],
    "By Recipient": [],
    "Carat": [],
}

export const mobileFilterStyles = {
    "Style": [
		{label: "Classic Solitaire", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Halo Rings", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Side Stone Rings", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Three Stone Rings", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Illusion Set Rings", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Toi Et Moi", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Couples", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Trilogy Rings", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Twisted Rings", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Gemstone", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Diamond Band", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Unique", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Unusual", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Antique", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Vintage", image: "/assets/images/solitaire.avif", type: "image"},
		{label: "Minimalist", image: "/assets/images/solitaire.avif"}
	],
	"Metal":[{label: "Classic Solitaire", image: "/assets/images/solitaire.avif"},
		{label: "Halo Rings", image: "/assets/images/solitaire.avif"},
		{label: "Side Stone Rings", image: "/assets/images/solitaire.avif"},
		{label: "Three Stone Rings", image: "/assets/images/solitaire.avif"},
		{label: "Illusion Set Rings", image: "/assets/images/solitaire.avif"},
		{label: "Toi Et Moi", image: "/assets/images/solitaire.avif"},
		{label: "Couples", image: "/assets/images/solitaire.avif"},
		{label: "Trilogy Rings", image: "/assets/images/solitaire.avif"},
		{label: "Twisted Rings", image: "/assets/images/solitaire.avif"},
		{label: "Gemstone", image: "/assets/images/solitaire.avif"},
		{label: "Diamond Band", image: "/assets/images/solitaire.avif"},
		{label: "Unique", image: "/assets/images/solitaire.avif"},
		{label: "Unusual", image: "/assets/images/solitaire.avif"},
		{label: "Antique", image: "/assets/images/solitaire.avif"},
		{label: "Vintage", image: "/assets/images/solitaire.avif"},
		{label: "Minimalist", image: "/assets/images/solitaire.avif"}],
	"Stonetype":[{label: "Classic Solitaire", image: "/assets/images/solitaire.avif"},
		{label: "Halo Rings", image: "/assets/images/solitaire.avif"},
		{label: "Side Stone Rings", image: "/assets/images/solitaire.avif"},
		{label: "Three Stone Rings", image: "/assets/images/solitaire.avif"},
		{label: "Illusion Set Rings", image: "/assets/images/solitaire.avif"},
		{label: "Toi Et Moi", image: "/assets/images/solitaire.avif"},
		{label: "Couples", image: "/assets/images/solitaire.avif"},
		{label: "Trilogy Rings", image: "/assets/images/solitaire.avif"},
		{label: "Twisted Rings", image: "/assets/images/solitaire.avif"},
		{label: "Gemstone", image: "/assets/images/solitaire.avif"},
		{label: "Diamond Band", image: "/assets/images/solitaire.avif"},
		{label: "Unique", image: "/assets/images/solitaire.avif"},
		{label: "Unusual", image: "/assets/images/solitaire.avif"},
		{label: "Antique", image: "/assets/images/solitaire.avif"},
		{label: "Vintage", image: "/assets/images/solitaire.avif"},
		{label: "Minimalist", image: "/assets/images/solitaire.avif"}],
	"Shape":[{label: "Classic Solitaire", image: "/assets/images/solitaire.avif"},
		{label: "Halo Rings", image: "/assets/images/solitaire.avif"},
		{label: "Side Stone Rings", image: "/assets/images/solitaire.avif"},
		{label: "Three Stone Rings", image: "/assets/images/solitaire.avif"},
		{label: "Illusion Set Rings", image: "/assets/images/solitaire.avif"},
		{label: "Toi Et Moi", image: "/assets/images/solitaire.avif"},
		{label: "Couples", image: "/assets/images/solitaire.avif"},
		{label: "Trilogy Rings", image: "/assets/images/solitaire.avif"},
		{label: "Twisted Rings", image: "/assets/images/solitaire.avif"},
		{label: "Gemstone", image: "/assets/images/solitaire.avif"},
		{label: "Diamond Band", image: "/assets/images/solitaire.avif"},
		{label: "Unique", image: "/assets/images/solitaire.avif"},
		{label: "Unusual", image: "/assets/images/solitaire.avif"},
		{label: "Antique", image: "/assets/images/solitaire.avif"},
		{label: "Vintage", image: "/assets/images/solitaire.avif"},
		{label: "Minimalist", image: "/assets/images/solitaire.avif"}],
	"Setting Type":[],
    "By Recipient": [],
    "Carat": [],
}